[project]
name = "parentalcontrol"
version = "1.0.3"
description = "Parental Control Google Sheets Schedule Enforcer & System Daemon for Ubuntu"
readme = "README.md"
authors = [
    { name = "Atul Mahankal", email = "atulmahankal@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-auth>=2.57.0",
    "gspread>=6.2.1",
    "python-dateutil>=2.9.0.post0",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
    "tabulate>=0.10.0",
]

[project.scripts]
parentalcontrol = "parentalcontrol:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
